# Generated by Django 3.2.12 on 2023-08-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230817_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='favorite_foods',
            field=models.ManyToManyField(to='main_app.Food'),
        ),
    ]
